<a href="https://colab.research.google.com/github/yharshityadav/DATA-SCIENCE-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrix Manipulation in Python**


---


**Operation on Matrix**

1) .add() - This function is used to perform element wise matrix addtion

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.add(A,B)

array([[ 6,  8],
       [10, 12]])

2) .subtract() = This function is used to perform element wise matrix substraction

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.subtract(A,B)

array([[-4, -4],
       [-4, -4]])

3) .divide() - This function is used to perform element wise matrix division

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.divide(A,B)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

4) .multiply() - This function is used to perform element wise matrix multiplication

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

5) .dot() - This function is used to compute the amtrix multiplication, rather than element wise multiplication

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

6) .sqrt() - This function is used to compute the square root of each element of matrix

In [ ]:
A = np.array([[1,2],[3,4]])
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

7) .Sum(x,axis) - This function is used to add all element in matrix. Optional "axis" argument computes the column sum if axis is 0 and row sum if axis is 1

In [ ]:
A = np.array([[1,2],[3,4]])
print(np.sum(A))
print(np.sum(A,axis=0))
print(np.sum(A,axis=1))

10
[4 6]
[3 7]


8) "T" - This argument is used to transpose the specified matrix

In [24]:
A = np.array([[1,2],[3,4]])
A.T

array([[1, 3],
       [2, 4]])

In [26]:
A = np.array([[1,2],[3,4]])
np.transpose(A)

array([[1, 3],
       [2, 4]])

9) .empty() - This function is used to perform a operation in which it make a empty matrix according to argument which you want to pass

In [30]:
np.empty((2,3))

array([[5.57257149e-315, 0.00000000e+000, 1.50008929e+248],
       [1.50008929e+248, 5.95139232e+228, 3.12701935e-085]])

10) .ones() - This function is used to perform a operation in which it make a matrix which have only value "1" according to argument which you want to pass

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

11) .zeros() - This function is used to perform a operation in which it make a matrix which have only value "0" according to argument which you want to pass

In [34]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

12) .eye() - This function is used to perform a operation in which it make a matrix in which (N - no. of rows; M - no. of columns; K - index of matrix)

In [41]:
print(np.eye(2,k=0, dtype = int))
print(np.eye(N = 3, M = 4, k = 2, dtype = int))

[[1 0]
 [0 1]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


13) .identity() - This function is used to perform a operation in which it make a identity matrix according to argument which you want to pass

In [43]:
print(np.identity(3, dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


NameError: name 'la' is not defined