<a href="https://colab.research.google.com/github/yharshityadav/DATA-SCIENCE-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrix Manipulation in Python**


---


**Operation on Matrix**

1) .add() - This function is used to perform element wise matrix addtion

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.add(A,B)

array([[ 6,  8],
       [10, 12]])

2) .subtract() = This function is used to perform element wise matrix substraction

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.subtract(A,B)

array([[-4, -4],
       [-4, -4]])

3) .divide() - This function is used to perform element wise matrix division

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.divide(A,B)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

4) .multiply() - This function is used to perform element wise matrix multiplication

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.multiply(A,B)

array([[ 5, 12],
       [21, 32]])

5) .dot() - This function is used to compute the amtrix multiplication, rather than element wise multiplication

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

6) .sqrt() - This function is used to compute the square root of each element of matrix

In [ ]:
A = np.array([[1,2],[3,4]])
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

7) .Sum(x,axis) - This function is used to add all element in matrix. Optional "axis" argument computes the column sum if axis is 0 and row sum if axis is 1

In [ ]:
A = np.array([[1,2],[3,4]])
print(np.sum(A))
print(np.sum(A,axis=0))
print(np.sum(A,axis=1))

10
[4 6]
[3 7]


8) "T" - This argument is used to transpose the specified matrix

In [ ]:
A = np.array([[1,2],[3,4]])
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
A = np.array([[1,2],[3,4]])
np.transpose(A)

array([[1, 3],
       [2, 4]])

9) .empty() - This function is used to perform a operation in which it make a empty matrix according to argument which you want to pass

In [ ]:
np.empty((2,3))

array([[5.57257149e-315, 0.00000000e+000, 1.50008929e+248],
       [1.50008929e+248, 5.95139232e+228, 3.12701935e-085]])

10) .ones() - This function is used to perform a operation in which it make a matrix which have only value "1" according to argument which you want to pass

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

11) .zeros() - This function is used to perform a operation in which it make a matrix which have only value "0" according to argument which you want to pass

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

12) .eye() - This function is used to perform a operation in which it make a matrix in which (N - no. of rows; M - no. of columns; K - index of matrix)

In [ ]:
print(np.eye(2,k=0, dtype = int))
print(np.eye(N = 3, M = 4, k = 2, dtype = int))

[[1 0]
 [0 1]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


13) .identity() - This function is used to perform a operation in which it make a identity matrix according to argument which you want to pass

In [ ]:
print(np.identity(3, dtype = int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Creating Arrays Commands**


---

One Dimensional Array

From Python list    np.array([1,2,3,4,5,6])

Form Python Tuple   np.array((1,2,3,4,5,6))

Fromiter() Function np.fromiter((a for a in range(8)), float)



---

▶ Create a Numpy array from a list

A = [1,2,3,4]

print(np.array(A))

▶ Create a Numpy array from a tuple

B = (5,6,7,8)

print(np.array(B))

▶ Create a Numpy array using fromiter()

C = (a for a in range(8))

print(np.fromiter(C, float)



In [7]:
import numpy as np
print(np.array([1,2,3,4,5,6]))
print(np.array((1,2,3,4,5,6)))
print(np.fromiter((a for a in range(8)), float))
print(np.fromiter((a for a in range(8)), int))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0 1 2 3 4 5 6 7]


Multi - Dimensional Array

From Python Lists  np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

Using empty()      np.empty([4,3]. dtype = int)



---


▶ Create a Numpy array from a list

A = [1,2,3,4]

B = [5,6,7,8]

C = [9,10,11,12]

print(np.array([A, B, C])

▶ Create a Numpy array using numpy.empty()

print(np.empty([5,3], dtype = int)


In [12]:
print(np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]))
print(np.empty([5,3]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5.14042519e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.16100321e+156 1.50008929e+248]
 [4.31174539e-096 9.80058441e+252 1.23971686e+224]
 [2.59032973e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 6.32404027e-322]]


**Initial Placeholders**

One Dimensional Array



---

arange()             np.arange(1, 21)

linspace()           np.linspace(1, 21, 3)

zeros()              np.zeros(3, dtype = int)

ones()               np.ones(4, dype = int)

random.rand()        np.random.rand(4)

random.randint()     np.random.randint(6, size = 10)



---

▶ Create a Numpy array Using numpy.arange()

print(np.arange(1, 20))

▶ Create a Numpy array using numpy.linspace()

print(np.linspace(1, 20 3))

▶ Create a Numpy array using numpy.zeros()

print(np.zeros(4, dtype = int))

▶ Create a Numpy array using numpy.ones()

print(np.ones(3, dtype = int))

▶ Create a Numpy array using numpy.random.rand()

print(np.random.rand(3))

▶ Create a Numpy array using numpy.random,.randint()

print(np.random.randint(3, size = 10))

In [22]:
print(np.arange(1,20))
print(np.zeros(4, dtype =int))
print(np.ones(3, dtype = int))
print(np.linspace(1,10,5, dtype = int))
print(np.random.rand(4))
print(np.random.randint(5, size=10))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0]
[1 1 1]
[ 1  3  5  7 10]
[0.29659354 0.33100971 0.98074656 0.15663081]
[4 2 4 0 3 2 1 3 2 3]


In [26]:
print(np.zeros([2,4]))
print(np.ones([3,5]))
print(np.eye(4))
print(np.full(5,4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[4 4 4 4 4]


**Inspecting Properties**



---

Size                              arr.size()

length                            len(arr)

Shape                             arr.shape()

Datatype                          arr.dtype()

Changing Datatype of array        arr.stype('float64')

Converting array to list         arr.tolist()

checking dimension               aa.ndim()


In [44]:
A = np.array([[1,2,4,3],[3,4,5,4]])
print(np.size(A))
print(A.dtype)
print(np.shape(A))
print(np.ndim(A))
print(len(A))
print(A.astype('float64'))
print(A.tolist())


8
int64
(2, 4)
2
2
[[1. 2. 4. 3.]
 [3. 4. 5. 4.]]
[[1, 2, 4, 3], [3, 4, 5, 4]]


**Numpy Array Mathematics**

Arithmetic Operation

Add             np.add(A,B)

subtract        np.subtract(A,B)

Mutliply        np.multiply(A,B)

Divide          np.divide(A,B)

Modula          np.mod(A,B)

Remainder       np.remainder(A,B)

Power           np.power(A,B)

Exponent        np.exp(A)


In [55]:
A = np.array([1,2,3,4])
B = np.array([1,2,3,4])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.power(A,B))
print(np.exp(A))
print(np.remainder(A,B))
print(np.multiply(A,B))

[2 4 6 8]
[0 0 0 0]
[1. 1. 1. 1.]
[0 0 0 0]
[  1   4  27 256]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0 0 0 0]
[ 1  4  9 16]


**Comparison**

A = np.array([[1,2],[3,4]])

B = np.array([[1,2],[4,5]])

comparison = A == B

c = comparison.all()

print(c)

In [61]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[4,4]])
comparison = A == B
print(comparison)

C = comparison.all()
print(C)


[[ True  True]
 [False  True]]
False


**Vector Math**


---



Applying delete() method

print(np.delete(A, 0))

Applying sqrt() method

print(np.sqrt(A))

Applying absolute() method

print(np.abs(A))

Applying floor() method

print(np.floor(A))

Applying ceil() method

print(np.ceil(A))

Applying sin() method

print(np.sin(A))

Applying log() method

print(np.log(A))

Applying round() method

print(np.round(A))

In [67]:
A = np.array([1,2,3,4,5,6])
print(np.delete(A, 0))
print(np.log(A))
print(np.sin(A))
print(np.sqrt(A))
print(np.ceil(A))
print(np.floor(A))
print(np.round(A))
print(np.abs(A))


[2 3 4 5 6]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


**Statistic**


---

▶ Mean

print(np.mean(aar))

▶ Median

print(np.meadina(arr))

▶ Min and Max

print(np.min(arr))

print(np.max(arr))

▶ V:ariance

print(np.var(arr))

▶ Standard Deviation

print(np.std(arr))



---

Correlation coefficient


---

rslt = np.corrcoef(arr1,arr2)

print(rslt)


In [71]:
A = np.array([1,2,3,4])
print(np.mean(A))
print(np.median(A))
print(np.min(A))
print(np.max(A))
print(np.var(A))
print(np.std(A))
B = np.array([9,8,7,6])
print(np.corrcoef(A,B))

2.5
2.5
1
4
1.25
1.118033988749895
[[ 1. -1.]
 [-1.  1.]]
